config/routes.rb
Rails.application.routes.draw do

  resources :deliveries
  resources :user_subscriptions do
    member do
      get 'unsubscribe'
    end
  end
  resources :subscriptions
  resources :vkgroups
  root "pages#main"
  resources :reports
  resources :subscribes do
    member do
      get 'unsubscribe'
    end
  end
  devise_for :users, controllers: { registrations: "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users do
    member do
      get 'email'
    end
  end
  resources :questions do
    resources :answers
  end
  get '/rating', to: 'answers#rating'

  get '/new_time', to: 'answers#new_time'
  get '/check_time', to: 'answers#check_time'
  get '/offer', to: 'pages#offer'
  get '/faq', to: 'pages#faq'
  get '/endgame', to: 'pages#endgame'

  get '/play', to: 'pages#play'
  get '/vk', to: 'pages#vk'
  get '/vkusers', to: 'pages#vkusers'
  get '/vkdata', to: 'pages#vkdata'

end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, presence: true
  validates :text, presence: true
  validates :answer, presence: true
  validates :user_id, presence: true
  validates :audio, presence: true
  validates :time, presence: true

  mount_uploader :audio, AudioUploader
  mount_uploader :image, ImageUploader

  has_many :answers, dependent: :destroy
  has_many :reports, dependent: :destroy
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :subscribe!
  before_action :authenticate_user!
  before_action :admin_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    if current_user.is_admin?
      @questions = Question.all
    else
      @questions = Question.all.order(:time)
      @answers = current_user.answers
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answer = @question.answers.where(:user_id => current_user.id).first
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :text, :answer, :comment, :user_id, :audio, :time, :image)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper

  def current_question
    Question.where('time <= ?', (Time.now).strftime('%Y-%m-%d %H:%M:%S')).last
  end
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :answer %>
    <%= f.text_area :answer %>
  </div>
  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :time, "Дата(YYYY-MM-DD HH:MM:SS):"%>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :audio %>
    <%= f.file_field :audio %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<% provide :title, 'Вопросы' %>
<p id="notice"><%= notice %></p>

<h1>Вопросы</h1>
<br/>

<table class="table table-bordered">
    <thead>
        <tr class="info">
            <% if current_user.is_admin? %>
                <th>ID</th>
                <th>Название</th>
                <th>Время</th>
                <th colspan="3">Действия</th>
            <% else %>
                <th>Название</th>
                <th>Время публикации вопроса</th>
                <th>Ваш ответ</th>
                <th>Правильный ответ</th>
                <th>Вердикт</th>
            <% end %>
        </tr>
    </thead>
    <tbody>
        <% if current_user.is_admin? %>
            <% @questions.each do |question| %>
                <tr>
                    <td><%= question.id %></td>
                    <td><%= question.title %></td>
                    <td><%= question.time %></td>
                    <td><%= link_to 'Показать', question %></td>
                    <td><%= link_to 'Редактировать', edit_question_path(question) %></td>
                    <td><%= link_to 'Удалить', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
            <% end %>
        <% else %>
            <% @questions.each do |question| %>
                <% if question.time < current_question.time %>
                    <% answer = @answers.where(:question_id => question.id).first %>
                    <tr>
                        <td><%= link_to question.title, question %></td>
                        <td><%= (question.time - 1.hour).strftime("%d.%m.%Y %H:%M") %></td>
                        <td>
                            <% unless answer.nil? %>
                                <%= answer.text %>
                            <% end %>
                        </td>
                        <td>
                            <%= question.answer %>
                        </td>
                        <td>
                          <% unless answer.nil? %>
                              <% if answer.status %>
                                Правильный ответ
                              <% else %>
                                Отклонен
                              <% end %>
                          <% end %>
                        </td>
                    </tr>
                <% end %>
            <% end %>
        <% end %>
    </tbody>
</table>
<br>
<% if current_user.is_admin? %>
    <%= link_to 'Новый вопрос', new_question_path %>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<% if @question.time < current_question.time || current_user.is_admin? %>

    <% provide(:title, 'Вопрос дня, дата: ' + (@question.time - 1.hour).strftime('%d.%m.%Y').to_s) %>

    <p id="notice"><%= notice %></p>

    <% if @question.time != current_question.time %>
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <td>Название:</td>
                    <td><%= @question.title %></td>
                </tr>
                <tr>
                    <td>Опубликован:</td>
                    <td><%= (@question.time - 1.hour).strftime("%d.%m.%Y в %H:%M") %> по Московскому времени (UTC+3)</td>
                </tr>
                <tr>
                <tr>
                    <td>Аудио:</td>
                    <td><audio src="<%= @question.audio.url %>" id="audio" controls></audio></td>
                </tr>
                <tr>
                    <td>Текст:</td>
                    <td><%= @question.text %></td>
                </tr>
                <% if @question.image.url != nil %>
                <tr>
                    <td>Изображение:</td>
                    <td><%= image_tag @question.image.url %></td>
                </tr>
                <% end %>
                <tr id="answer" style="display: none;">
                    <td>Правильный ответ:</td>
                    <td>
                        <% if @question.time != current_question.time %>
                            <%= @question.answer %>
                        <% end %>
                    </td>
                </tr>
                <tr>
                    <td>Ваш ответ:</td>
                    <td>
                        <% if @answer != nil %>
                            <%= @answer.text %>
                        <% end %>
                    </td>
                </tr>
                <tr id="comment" style="display: none;">
                    <td>Комментарий:</td>
                    <td><%= @question.comment %></td>
                </tr>
            </tbody>
        </table>
        <a id="showbtn" class="btn btn-lg">Показать ответ и комментарий</a>
    <% else %>
      [это текущий вопрос дня, ответ недоступен до публикации следующего]
    <% end %>

    <% if current_user.is_admin? %>
        <table class="table table-bordered">
            <thead>
                <tr class="info">
                    <th>Имя Фамилия</th>
                    <th>Текст ответа</th>
                    <th>Время ответа</th>
                    <th colspan="2">Вердикты</th>
                    <th>Удаление</th>
                </tr>
            </thead>
            <tbody>
                <% @question.answers.where("status IS NULL").each do |answer| %>
                    <tr id="<%= answer.id %>">
                        <td><%= answer.user.name %> <%= answer.user.surname %> (<%= answer.user.id %>)</td>
                        <td><%= answer.text %></td>
                        <td><%= answer.created_at.strftime("%d.%m.%Y, в %H:%M") %></td>
                        <td>
                            <%= form_for [@question, answer], remote: true do |f| %>
                                <%= f.hidden_field :status, value: false %>
                                <%= f.submit value: "Отклонить" %>
                            <% end %>
                        </td>
                        <td>
                            <%= form_for [@question, answer], remote: true do |f| %>
                                <%= f.hidden_field :status, value: true %>
                                <%= f.submit value: "Принять" %>
                            <% end %>
                        </td>
                        <td>
                            <%= link_to 'Удалить', question_answer_path(answer.question, answer), method: :delete, data: { confirm: 'Вы уверены?' }, remote: true %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <%= link_to 'Редактировать', edit_question_path(@question) %> |
        <%= link_to 'Назад', questions_path %>
    <% end %>
<% end %>
<script language="javascript">
    $("#showbtn").click(function(){
        $("#answer").show();
        $("#comment").show();
        $("#showbtn").remove();
    });
</script>