config/routes.rb
Rails.application.routes.draw do

  resources :deliveries
  resources :user_subscriptions do
    member do
      get 'unsubscribe'
    end
  end
  resources :subscriptions
  resources :vkgroups
  root "pages#main"
  resources :reports
  resources :subscribes do
    member do
      get 'unsubscribe'
    end
  end
  devise_for :users, controllers: { registrations: "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users do
    member do
      get 'email'
    end
  end
  resources :questions do
    resources :answers
  end
  get '/rating', to: 'answers#rating'

  get '/new_time', to: 'answers#new_time'
  get '/check_time', to: 'answers#check_time'
  get '/offer', to: 'pages#offer'
  get '/faq', to: 'pages#faq'
  get '/endgame', to: 'pages#endgame'

  get '/play', to: 'pages#play'
  get '/vk', to: 'pages#vk'
  get '/vkusers', to: 'pages#vkusers'
  get '/vkdata', to: 'pages#vkdata'

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = current_user.reports.build(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
        format.js{}
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
        format.js{}
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:tech_comment, :tech_rate, :audio_comment, :audio_rate, :question_comment, :question_rate, :equip_comment, :sentence, :user_id, :question_id)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tech_comment %><br>
    <%= f.text_area :tech_comment %>
  </div>
  <div class="field">
    <%= f.label :tech_rate %><br>
    <%= f.number_field :tech_rate %>
  </div>
  <div class="field">
    <%= f.label :audio_comment %><br>
    <%= f.text_area :audio_comment %>
  </div>
  <div class="field">
    <%= f.label :audio_rate %><br>
    <%= f.number_field :audio_rate %>
  </div>
  <div class="field">
    <%= f.label :question_comment %><br>
    <%= f.text_area :question_comment %>
  </div>
  <div class="field">
    <%= f.label :question_rate %><br>
    <%= f.number_field :question_rate %>
  </div>
  <div class="field">
    <%= f.label :equip_comment %><br>
    <%= f.text_area :equip_comment %>
  </div>
  <div class="field">
    <%= f.label :sentence %><br>
    <%= f.text_area :sentence %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/create.js.erb
$("#new_report").remove();

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reports</h1>
<table class="table table-bordered">
  <tbody>
      <tr>
        <td>Качество технической стороны:</td>
        <td><%= @reports.average(:tech_rate) %></td>
      </tr>
      <tr>
        <td>Качество аудиозаписи:</td>
        <td><%= @reports.average(:audio_rate) %></td>
      </tr>
      <tr>
        <td>Качество вопроса:</td>
        <td><%= @reports.average(:question_rate) %></td>
      </tr>
  </tbody>
</table>
<br/>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Id</th>
      <th>Question</th>
      <th>User</th>
      <th>Tech rate</th>
      <th>Audio rate</th>
      <th>Qiestion rate</th>
      <th>Devise</th>
<<<<<<< HEAD
      <th>Delete</th>
      <td>Time</td>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= link_to report.id, report_path(report) %></td>
        <td><%= report.question.id %></td>
        <td><%= report.user.name %> <%=report.user.surname %>(<%= report.user.id %>)</td>
        <td><%= report.tech_rate %></td>
        <td><%= report.audio_rate %></td>
        <td><%= report.question_rate %></td>
        <td><%= link_to report.equip_comment, report_path(report) %></td>
        <td><%= link_to 'Удалить', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= report.created_at.strftime("%d.%m.%Y, в %H:%M") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tech comment:</strong>
  <%= @report.tech_comment %>
</p>

<p>
  <strong>Tech rate:</strong>
  <%= @report.tech_rate %>
</p>

<p>
  <strong>Audio comment:</strong>
  <%= @report.audio_comment %>
</p>

<p>
  <strong>Audio rate:</strong>
  <%= @report.audio_rate %>
</p>

<p>
  <strong>Question comment:</strong>
  <%= @report.question_comment %>
</p>

<p>
  <strong>Question rate:</strong>
  <%= @report.question_rate %>
</p>

<p>
  <strong>Equp comment:</strong>
  <%= @report.equip_comment %>
</p>

<p>
  <strong>Sentence:</strong>
  <%= @report.sentence %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>