config/routes.rb
Rails.application.routes.draw do

  resources :deliveries
  resources :user_subscriptions do
    member do
      get 'unsubscribe'
    end
  end
  resources :subscriptions
  resources :vkgroups
  root "pages#main"
  resources :reports
  resources :subscribes do
    member do
      get 'unsubscribe'
    end
  end
  devise_for :users, controllers: { registrations: "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users do
    member do
      get 'email'
    end
  end
  resources :questions do
    resources :answers
  end
  get '/rating', to: 'answers#rating'

  get '/new_time', to: 'answers#new_time'
  get '/check_time', to: 'answers#check_time'
  get '/offer', to: 'pages#offer'
  get '/faq', to: 'pages#faq'
  get '/endgame', to: 'pages#endgame'

  get '/play', to: 'pages#play'
  get '/vk', to: 'pages#vk'
  get '/vkusers', to: 'pages#vkusers'
  get '/vkdata', to: 'pages#vkdata'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :text, presence: true
  validates :question_id, presence: true
  validates :user_id, presence: true

  belongs_to :question
  belongs_to :user
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, presence: true
  validates :text, presence: true
  validates :answer, presence: true
  validates :user_id, presence: true
  validates :audio, presence: true
  validates :time, presence: true

  mount_uploader :audio, AudioUploader
  mount_uploader :image, ImageUploader

  has_many :answers, dependent: :destroy
  has_many :reports, dependent: :destroy
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/models/subscribe.rb
class Subscribe < ActiveRecord::Base
  validates :email, presence: true
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  has_many :user_subscriptions
  has_many :users, through: :user_subscriptions
end

app/models/user.rb
class User < ActiveRecord::Base

  establish_connection 'mind'

  include QuestionsHelper

# Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :questions
  has_many :answers, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :user_subscriptions, foreign_key: "user_id"
  has_many :subs, through: :user_subscriptions, :source => :subscription

  def is_admin?
    self.is_admin
  end

  def rating
    self.answers.includes(:question)
        .where('questions.time < ?', current_question.time).references(:questions)
        .where(:status => true)
        .count
  end

  def self.find_for_facebook_oauth(access_token, writename)
    if user = User.where(:email => access_token.extra.raw_info.email).first || user = User.where(:fb => access_token.extra.raw_info.id).first
      if writename
        user.name = access_token.info.first_name
        user.surname = access_token.info.last_name
      end
      user.fb = access_token.extra.raw_info.id
      user.save
      user
    else
      logger.info "#{access_token}"
      if access_token.extra.raw_info.email.nil?
        User.create!(:name => access_token.info.first_name, :surname => access_token.info.last_name, :provider => access_token.provider, :username => access_token.extra.raw_info.name, :nickname => access_token.extra.raw_info.username, :email => rand.to_s + '@fb.com', :password => Devise.friendly_token[0,20])
      else
        User.create!(:name => access_token.info.first_name, :surname => access_token.info.last_name, :provider => access_token.provider, :username => access_token.extra.raw_info.name, :nickname => access_token.extra.raw_info.username, :email => access_token.extra.raw_info.email, :password => Devise.friendly_token[0,20])
      end
    end
  end

  def self.find_for_vkontakte_oauth(access_token, writename)
    if user = User.where(:email => access_token.info.email).first || user = User.where(:vk => access_token.extra.raw_info.id).first
      if writename
        user.name = access_token.info.first_name
        user.surname = access_token.info.last_name
      end
      user.vk = access_token.extra.raw_info.id
      user.save
      user
    else
      if access_token.info.email.nil?
        User.create!(:name => access_token.info.first_name, :surname => access_token.info.last_name, :provider => access_token.provider, :url => access_token.info.urls.Vkontakte, :username => access_token.info.name, :nickname => access_token.extra.raw_info.domain, :email => rand.to_s + '@vk.com', :password => Devise.friendly_token[0,20])
      else
        User.create!(:name => access_token.info.first_name, :surname => access_token.info.last_name, :provider => access_token.provider, :url => access_token.info.urls.Vkontakte, :username => access_token.info.name, :nickname => access_token.extra.raw_info.domain, :email => access_token.info.email, :password => Devise.friendly_token[0,20])
      end
    end
  end
end

app/models/user_subscription.rb
class UserSubscription < ActiveRecord::Base

  validates :token, presence: true

  belongs_to :user
  belongs_to :subscription
end

app/models/vkgroup.rb
class Vkgroup < ActiveRecord::Base
end

app/models/vkuser.rb
class Vkuser < ActiveRecord::Base
  validates :vk_id, uniqueness: true
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_filter :empty_mail!

  def main
    if current_user 
      unless session[:last_question].nil? 
        @question = Question.find(session[:last_question])
        @answer = @question.answers.new(:text => session[:last_question_text], :user_id => current_user.id)
        @answer.save
        session[:last_question] = nil
        session[:last_question_text] = nil
      end
    end
    @answer = Answer.new
    @subscribe = Subscribe.new
  end

  def play
    if current_user 
      unless session[:last_question].nil? 
        @question = Question.find(session[:last_question])
        @answer = @question.answers.new(:text => session[:last_question_text], :user_id => current_user.id)
        @answer.save
        session[:last_question] = nil
        session[:last_question_text] = nil
      end
    end
    @answer = Answer.new
    @subscribe = Subscribe.new
    @report = Report.new
  end

  def vk
    @vk = VkontakteApi::Client.new(session['vk_token'])
  end

  def vkusers
    @vkgroups = Vkgroup.all
    @vkgroups.each do |g|
      Vkuser.create(vk_id: g.user_id)
    end
    render text: 'Done!'
  end

  def vkdata
    @vk = VkontakteApi::Client.new(session['vk_token'])
    @vkusers = Vkuser.all
    @vkusers.each do |u|
      sleep 0.34
      vk = @vk.execute(code: 'return API.users.get({user_ids:' + u.vk_id + ', fields: "sex,bdate"});').to_a
      u.name = vk[0].first_name
      u.surname = vk[0].last_name
      u.sex = vk[0].sex
      u.bdate = vk[0].bdate
      u.save
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(title)
    if title.nil?
      title = 'Вопрос дня'
    end
    title
  end

  def subscribe!
    if request.original_fullpath !='/' && request.original_fullpath != '/users/sign_in'
      unless current_user
        redirect_to root_path
      end
    end
  end

  include UsersHelper
  include QuestionsHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper

  def current_question
    Question.where('time <= ?', (Time.now).strftime('%Y-%m-%d %H:%M:%S')).last
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/subscribes_helper.rb
module SubscribesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  def resource_class
    devise_mapping.to
  end

  def admin_user!
    unless current_user.is_admin?
      redirect_to root_path
    end
  end

  def empty_mail!
    if current_user && (current_user.email['vk.com'] == 'vk.com' || current_user.email['fb.com'] == 'fb.com')
      redirect_to email_user_path(current_user)
    end
  end
end

app/helpers/vkgroups_helper.rb
module VkgroupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title><%= title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
    <%= csrf_meta_tags %>
    <link rel="apple-touch-icon" sizes="57x57" href="/images/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/images/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/images/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/images/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/images/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/images/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" href="/images/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/images/favicon-194x194.png" sizes="194x194">
    <link rel="icon" type="image/png" href="/images/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="/images/android-chrome-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="/images/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/images/manifest.json">
    <link rel="shortcut icon" href="/images/favicon.ico">
    <meta name="msapplication-TileColor" content="#ffc40d">
    <meta name="msapplication-TileImage" content="/images/mstile-144x144.png">
    <meta name="msapplication-config" content="/images/browserconfig.xml">
    <meta name="theme-color" content="#1882b0">

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="/bootstrap.css" media="screen">
    <link rel="stylesheet" href="/bootswatch.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
<div class="navbar navbar-fixed-top navbar-default navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Вопрос дня', root_path %></li>
            <li><%= link_to 'Рейтинг', 'http://qd.mindpowergame.com/rating' %></li>
            <% if current_user %><li>
               <li><%= link_to 'Вопросы', questions_path %></li>
               <% if current_user.is_admin? %>
                 <li><%= link_to 'Пользователи', users_path %></li>
                 <li><%= link_to 'Отчёты', reports_path %></li>
                 <li><%= link_to 'Подписчики', subscribes_path %></li>
               <% end %>
           <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
                <li>
                  <%= link_to current_user.name + " " + current_user.surname, user_path(current_user) %>
                </li>
              <li>
		            <%= link_to 'Выход', destroy_user_session_path, method: :delete %>
                </li>
            <% else %>
              <li><%= link_to 'Вход', new_user_session_path %></li>
            <% end %>
          </ul>
	      </div>
      </div>
     </div>
	  <br/>
  <div id="wrapper">
    <div class="container">
      <div>
        <div class="row">
          <div class="col-lg-9">
            <%= yield %>
          </div>
          <div class="col-lg-3">
            <%= render 'layouts/friends' %>
          </div>
        </div>
      </div>
    </div>
  </div>
   <footer>
        <div class="container">
      <div class="row">
          <p>&copy; Вопрос дня &mdash; интеллектуальная разминка на каждый день, 2015</p>
          <p>Авторы &mdash; Максим Тепленёв, Вячеслав Гаранович</p>
        </div>
      </div>
    </footer>
    <!-- HelloPreload http://hello-site.ru/preloader/ -->
    <!-- 
    <style type="text/css">#hellopreloader>p{display:none;}#hellopreloader_preload{display: block;position: fixed;z-index: 99999;top: 0;left: 0;width: 100%;height: 100%;min-width: 1000px;background: #4183D7 url(http://hello-site.ru//main/images/preloads/tail-spin.svg) center center no-repeat;background-size:300px;}</style>
    <div id="hellopreloader"><div id="hellopreloader_preload"></div><p><a href="http://hello-site.ru">Hello-Site.ru. Бесплатный конструктор сайтов.</a></p></div>
    <script type="text/javascript">var hellopreloader = document.getElementById("hellopreloader_preload");function fadeOutnojquery(el){el.style.opacity = 1;var interhellopreloader = setInterval(function(){el.style.opacity = el.style.opacity - 0.05;if (el.style.opacity <=0){ clearInterval(interhellopreloader);hellopreloader.style.display = "none";}},16);}window.onload = function(){setTimeout(function(){fadeOutnojquery(hellopreloader);},1000);};</script>
-->
    <!-- HelloPreload http://hello-site.ru/preloader/ -->

    <!-- <script type="text/javascript">(function() {
    if (window.pluso)if (typeof window.pluso.start == "function") return;
    if (window.ifpluso==undefined) { window.ifpluso = 1;
    var d = document, s = d.createElement('script'), g = 'getElementsByTagName';
    s.type = 'text/javascript'; s.charset='UTF-8'; s.async = true;
    s.src = ('https:' == window.location.protocol ? 'https' : 'http') + '://share.pluso.ru/pluso-like.js';
    var h=d[g]('body')[0];
    h.appendChild(s);
    }})();</script> -->

    <!-- Yandex.Metrika counter --><script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter31182506 = new Ya.Metrika({ id:31182506, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="https://mc.yandex.ru/watch/31182506" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->
    <!-- BEGIN JIVOSITE CODE {literal} -->
    <script type='text/javascript'>
    (function(){ var widget_id = 'qAX0wKB86D';
    var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = '//code.jivosite.com/script/widget/'+widget_id; var ss = document.getElementsByTagName('script')[0]; ss.parentNode.insertBefore(s, ss);})();</script>
    <!-- {/literal} END JIVOSITE CODE -->
  </body>
</html>

app/views/layouts/application.html2.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title><%= title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
    <%= csrf_meta_tags %>
<link rel="apple-touch-icon" sizes="57x57" href="/images/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/images/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/images/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/images/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/images/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/images/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/images/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/images/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="/images/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/images/favicon-194x194.png" sizes="194x194">
<link rel="icon" type="image/png" href="/images/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/images/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="/images/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/images/manifest.json">
<link rel="shortcut icon" href="/images/favicon.ico">
<meta name="msapplication-TileColor" content="#ffc40d">
<meta name="msapplication-TileImage" content="/images/mstile-144x144.png">
<meta name="msapplication-config" content="/images/browserconfig.xml">
<meta name="theme-color" content="#1882b0">

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="/bootstrap.css" media="screen">
    <link rel="stylesheet" href="/bootswatch.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
<div class="navbar navbar-fixed-top navbar-default navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Вопрос дня', root_path %></li>
            <li><%= link_to 'Рейтинг', 'http://qd.mindpowergame.com/rating' %></li>
            <% if current_user %><li>
               <li><%= link_to 'Вопросы', questions_path %></li>
               <% if current_user.is_admin? %>
                 <li><%= link_to 'Пользователи', users_path %></li>
                 <li><%= link_to 'Отчёты', reports_path %></li>
                 <li><%= link_to 'Подписчики', subscribes_path %></li>
               <% end %>
           <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
                <li>
                  <%= link_to current_user.name + " " + current_user.surname, user_path(current_user) %>
                </li>
              <li>
		            <%= link_to 'Выход', destroy_user_session_path, method: :delete %>
                </li>
            <% else %>
              <li><%= link_to 'Вход', new_user_session_path %></li>
            <% end %>
          </ul>
	      </div>
      </div>
     </div>
	  </div>
	  <br/>
  <div id="wrapper">
    <div class="container">
      <div>
        <div class="row">
          <div class="col-lg-12">
          <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </div>
   <footer>
      <div class="row">
        <div class="container">
          <p>&copy; Вопрос дня &mdash; интеллектуальная разминка на каждый день, 2015</p>
          <p>Авторы &mdash; Максим Тепленёв, Вячеслав Гаранович</p>
        </div>
      </div>
    </footer>
    <!-- HelloPreload http://hello-site.ru/preloader/ -->
    <style type="text/css">#hellopreloader>p{display:none;}#hellopreloader_preload{display: block;position: fixed;z-index: 99999;top: 0;left: 0;width: 100%;height: 100%;min-width: 1000px;background: #4183D7 url(http://hello-site.ru//main/images/preloads/tail-spin.svg) center center no-repeat;background-size:300px;}</style>
    <div id="hellopreloader"><div id="hellopreloader_preload"></div><p><a href="http://hello-site.ru">Hello-Site.ru. Бесплатный конструктор сайтов.</a></p></div>
    <script type="text/javascript">var hellopreloader = document.getElementById("hellopreloader_preload");function fadeOutnojquery(el){el.style.opacity = 1;var interhellopreloader = setInterval(function(){el.style.opacity = el.style.opacity - 0.05;if (el.style.opacity <=0){ clearInterval(interhellopreloader);hellopreloader.style.display = "none";}},16);}window.onload = function(){setTimeout(function(){fadeOutnojquery(hellopreloader);},1000);};</script>
    <!-- HelloPreload http://hello-site.ru/preloader/ -->

    <!-- <script type="text/javascript">(function() {
    if (window.pluso)if (typeof window.pluso.start == "function") return;
    if (window.ifpluso==undefined) { window.ifpluso = 1;
    var d = document, s = d.createElement('script'), g = 'getElementsByTagName';
    s.type = 'text/javascript'; s.charset='UTF-8'; s.async = true;
    s.src = ('https:' == window.location.protocol ? 'https' : 'http') + '://share.pluso.ru/pluso-like.js';
    var h=d[g]('body')[0];
    h.appendChild(s);
    }})();</script> -->

    <!-- Yandex.Metrika counter --><script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter31182506 = new Ya.Metrika({ id:31182506, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="https://mc.yandex.ru/watch/31182506" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->
    <!-- BEGIN JIVOSITE CODE {literal} -->
    <script type='text/javascript'>
    (function(){ var widget_id = 'qAX0wKB86D';
    var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = '//code.jivosite.com/script/widget/'+widget_id; var ss = document.getElementsByTagName('script')[0]; ss.parentNode.insertBefore(s, ss);})();</script>
    <!-- {/literal} END JIVOSITE CODE -->
  </body>
</html>

app/views/pages/mai4n.html.erb
<% provide(:title, "Вопрос дня") %>
<style>
#quest_text{
  font-size: 17px;
}

#quest_img{
  max-height: 250px;
}

body{
  background: url(<%= asset_path("bg.jpg") %>);
  background-size: cover;
}

body > .navbar {
  opacity: 0.6;
  background: rgba(0,0,0,0);
  box-shadow: none !important;
}

.navbar-inverse .navbar-nav > li > a {
  color: #fff !important;
}

.navbar-inverse .navbar-nav > li > a:hover {
    color: #000000;
}

footer {
  box-shadow: none !important;
  background: none !important;
  border-top: none !important;
  opacity: 0.7;
  color: #fff;
}

footer .row {
    padding-bottom: 0 !important;
}

#zet{
  position: relative;
  padding: 0;
}

#zet h1 {
  /*width: 650px;*/
  color: #fff;
  font-size: 47pt;
  font-family: 'pfhighway' !important;
  text-shadow: 1px 1px 2px rgba(0,0,0,0.2);
}

#zet p {
  color: #fff;
  font-size: 15pt;
  font-family: 'pfhighway' !important;
  line-height: 30px;
}

#zet #play {
  color: #fff;
  background: #BD9C7C;
  border-radius: 0;
  border: 1px solid #fff;
}

.play {
    color: #fff;
    background: #BD9C7C;
    border-radius: 0 !important;
    display: inline;
    border: 1px solid #fff;
}
.btn-lg, .btn-group-lg > .btn {
  padding: 20px 75px;
  font-size: 27px;
  line-height: 1.3333333;
  border-radius: 6px;
}
.input-lg {
    height: 78px;
    padding: 14px 10px;
    border: none;
    border-radius: 0;
    vertical-align: bottom;
}

@media screen and (max-width: 768px){
    body {
        background-image: none !important;
        background: #fff !important;

    }
    body > .navbar {
        opacity: 1 !important;
        background: #fff;
    }
    .navbar-inverse .navbar-nav > li > a {
        color: #000 !important;
    }
    #zet h1 {
        color: #000;
    }

    #zet p {
        color: #000;
    }
}
</style>
<% unless current_question.nil? %>


  <div id="zet" class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
    <!--
    <center>
      <p>Играть Вопрос дня на <%= current_question.time.strftime("%d.%m.%Y") %></p>
    </center>
    -->
    <h1 class="col-xs-12 col-sm-8 col-lg-12">Интеллектуальная разминка на каждый день</h1>
    <p class="col-lg-8 col-sm-8 col-xs-8">
        Каждый день подписчикам проекта становится доступен бесплатный вопрос, которого нет в интернет-базах вопросов. Удобный и познавательный способ саморазвития всего за 5 минут в день. Отвечайте на вопросы сами, командой или семьей!
        <br/><br/>
    <% if current_user %>
        Вы успешно зарегистрированы в бета-тестировании проекта. Для начала игры нажмите на кнопку:</p><br/>
        <!--<button id="play" class="btn btn-lg">Играть «Вопрос дня»!</button>-->
	<%= link_to "Перейти к игре", play_path, class: "btn btn-lg play col-lg-6" %>
    <% else %>
        <p class="col-lg-8 col-sm-8 col-xs-8">Зарегистрируйтесь как игрок в режиме бета-тестирования:</p><br/>
	<p class="col-lg-8 col-sm-8 col-xs-8"><%= link_to "Регистрация", "http://qd.mindpowergame.com/users/sign_up", class: "btn btn-lg play col-lg-6" %></p>
    <% end %>
    
  </div>
<% end %>